// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRYgqwvuFfPJTrYNZx5wavycdkvhcBhII',
    appId: '1:757143187725:web:ed3636c741c2a22b140044',
    messagingSenderId: '757143187725',
    projectId: 'hello-chat-app-6ef71',
    authDomain: 'hello-chat-app-6ef71.firebaseapp.com',
    storageBucket: 'hello-chat-app-6ef71.firebasestorage.app',
    measurementId: 'G-50VRYBL8D4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAul_ijmq8fKGt-eXnfn4kbYwvjv-ogD2Y',
    appId: '1:757143187725:android:a168f85e2db96e1f140044',
    messagingSenderId: '757143187725',
    projectId: 'hello-chat-app-6ef71',
    storageBucket: 'hello-chat-app-6ef71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkz39jAO_R78Hqsf7YL-Anm-sM1F219Xg',
    appId: '1:757143187725:ios:967427c17d00cdaf140044',
    messagingSenderId: '757143187725',
    projectId: 'hello-chat-app-6ef71',
    storageBucket: 'hello-chat-app-6ef71.firebasestorage.app',
    iosBundleId: 'com.example.helloChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkz39jAO_R78Hqsf7YL-Anm-sM1F219Xg',
    appId: '1:757143187725:ios:967427c17d00cdaf140044',
    messagingSenderId: '757143187725',
    projectId: 'hello-chat-app-6ef71',
    storageBucket: 'hello-chat-app-6ef71.firebasestorage.app',
    iosBundleId: 'com.example.helloChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRYgqwvuFfPJTrYNZx5wavycdkvhcBhII',
    appId: '1:757143187725:web:f652bf4ce1013749140044',
    messagingSenderId: '757143187725',
    projectId: 'hello-chat-app-6ef71',
    authDomain: 'hello-chat-app-6ef71.firebaseapp.com',
    storageBucket: 'hello-chat-app-6ef71.firebasestorage.app',
    measurementId: 'G-D7Y8YWEHKX',
  );
}
